### PR TITLE
Update sqlstyle.guide.md

### PR DESCRIPTION
**Pull request by vanillajonathan**
Fix grammar. Proper hyphenation between words. Use HTTPS links.

### CODE REVIEW

**Comment by vanillajonathan** [comment]
Ping @treffynnon

**Comment by treffynnon** [comment]
> Ping @treffynnon

Apologies, I have not had a chance to look at this one yet. I need to take a proper look to ensure that I agree with all the changes.

**Comment by vanillajonathan** [comment]
@treffynnon Have you taken an look at it yet?

**Comment by treffynnon** [comment]
Sorry, no, I had not. Thanks for the fixes and the reminders.

**Pull request merged**
