### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by robertopauletto**
Here's the italian translation. in the new folder "it"
Thanks

### CODE REVIEW

**Comment by vanillajonathan** [comment]
You can also add the translation to the README.md file.
https://github.com/treffynnon/sqlstyle.guide#translations-of-the-guide

**Comment by treffynnon** [comment]
Thank you for opening the PR I've been very busy this week, but I will take
a look very soon. Apologies for the delay.

**Comment by robertopauletto** [comment]
No problem Simon, take your time

Bye

--
  Roberto Pauletto
  roberto.pauletto@gmail.com

**Comment by treffynnon** [comment]
Thanks for your work on the translation - I have merged it and its available over here: https://www.sqlstyle.guide/it/

**Comment by robertopauletto** [comment]
Thank you Simon.

I'have noticed that the title it's not italan (it's Galician according to Google)

The italian translation should be "Guida allo stile SQL"

I've created a pull request to fix some small typos.

Thank you again

--
  Roberto Pauletto
  roberto.pauletto@gmail.com

**Comment by treffynnon** [comment]
Baha Google told me that was the translation! I'll get it corrected ASAP,
thanks.

**Pull request merged**
